package com.generator.model;

import com.generator.model.enums.AttributeType;
import com.generator.model.enums.GenerationType;

public class Attribute {
	private String name;
	private AttributeType attributeType;
	private GenerationType generationType;
	private Enum<?> enumType;
	private boolean nullable;
	private boolean unique;
	private boolean autoGenerated;

	public Attribute() {
	}

	public Attribute(String name, AttributeType attributeType, boolean nullable, boolean autoGenerated) {
		super();
		this.name = name;
		this.attributeType = attributeType;
		this.nullable = nullable;
		this.autoGenerated = autoGenerated;
		this.generationType = GenerationType.AUTO;
		unique = false;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public AttributeType getAttributeType() {
		return attributeType;
	}

	public void setAttributeType(AttributeType attributeType) {
		this.attributeType = attributeType;
	}

	public boolean isNullable() {
		return nullable;
	}

	public void setNullable(boolean nullable) {
		this.nullable = nullable;
	}

	public boolean isAutoGenerated() {
		return autoGenerated;
	}

	public void setAutoGenerated(boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}

	public boolean isUnique() {
		return unique;
	}

	public void setUnique(boolean unique) {
		this.unique = unique;
	}

	public GenerationType getGenerationType() {
		return generationType;
	}

	public void setGenerationType(GenerationType generationType) {
		this.generationType = generationType;
	}

	public Enum<?> getEnumType() {
		return enumType;
	}

	public void setEnumType(Enum<?> enumType) {
		this.enumType = enumType;
	}
}
